#Plot 4
Data <- read.table ("household_power_consumption.txt", sep=";", header=TRUE)
Data$Date2 <- as.Date(Data$Date, "%d/%m/%Y")
DF <-   subset(Data, Date2 >= as.Date("01/02/2007", "%d/%m/%Y") & Date2 <= as.Date("02/02/2007", "%d/%m/%Y") )
DF$WeekDay <- format(DF$Date2, "%a")
DF$WeekDay <- as.factor(DF$WeekDay)
DF$Global_active_power <- as.numeric(DF$Global_active_power)
DF$Voltage <- as.numeric(DF$Voltage)
DF$Global_reactive_power <- as.numeric(DF$Global_reactive_power)
DF$TimeAll <- strptime(paste(DF$Date,DF$Time), "%d/%m/%Y %H:%M:%S")
png("plot4.png")
par(mfrow = c(2,2))
plot(DF$TimeAll, DF$Global_active_power, type="l",col="black", ylab="Global Active Power", main="", xlab="")
plot(DF$TimeAll, DF$Voltage, type="l",col="black", ylab="Voltage", xlab="datetime", main="")
with(DF, plot(TimeAll,Sub_metering_1, type="l",col="black", ylab="Energy sub metering", main="", xlab="" ))
with(DF, lines(TimeAll,Sub_metering_2,col="red"))
with(DF, lines(TimeAll,Sub_metering_3,col="blue"))
legend ("topright", pch="_", col=c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(DF$TimeAll, DF$Global_reactive_power, type="l",col="black", ylab="Global_reactive_power", xlab="datetime", main="")
dev.off()