#Plot 2
Data <- read.table ("household_power_consumption.txt", sep=";", header=TRUE)
Data$Date2 <- as.Date(Data$Date, "%d/%m/%Y")
DF <-   subset(Data, Date2 >= as.Date("01/02/2007", "%d/%m/%Y") & Date2 <= as.Date("02/02/2007", "%d/%m/%Y") )
DF$WeekDay <- format(DF$Date2, "%a")
DF$WeekDay <- as.factor(DF$WeekDay)
DF$Global_active_power <- as.numeric(DF$Global_active_power)
DF$Voltage <- as.numeric(DF$Voltage)
DF$Global_reactive_power <- as.numeric(DF$Global_reactive_power)
DF$TimeAll <- strptime(paste(DF$Date,DF$Time), "%d/%m/%Y %H:%M:%S")
png("plot2.png")
par(mfrow = c(1,1))
plot(DF$TimeAll, DF$Global_active_power, type="l",col="black", ylab="Global Active Power (kilowatts)", main="", xlab="")
dev.off()